### ISSUE TITLE
Custom rules/functions?

### ISSUE THREAD

**Issue by jeffijoe** [exjs/exmodel#1]
Super cool library, the code-generation aspect is brilliant!

Is it possible to define custom rules and/or validator functions?

**Comment by kobalicek** [comment]
Yeah, an example that describes what you need would be cool, but basically anything should be possible with the current code-base.

**Comment by jeffijoe** [comment]
Something along the lines of...

```
function beAwesome(value, key, obj) {
  // value = the value of the field
  // key = the property it was run on, e.g. `email`
  // obj = the object being validated.

  // Returns a boolean indicating success.
  return value.indexOf('awesome');
}

exmodel.schema({
  email: {
    $type: 'string',
    // "The email $must beAwesome"
    $must: beAwesome
  }
});
```

What are your thoughts?

**Comment by kobalicek** [comment]
I just checked it out and noticed that there is no function-like validator, so yeah, I will implement passing user defined functions to basic types. However, I'm not sure if the parent should be exposed, as there could be no "email" parent if it's a list of emails or it's a root type, not sure what to do in that case, leave key `null`?

**Comment by kobalicek** [comment]
Let me know if the `$fn` based approach works for you. I know it's a bit limited, but the compiler atm doesn't really use the parent object if compiling children validation. It's possible to implement it thought.

**Comment by jeffijoe** [comment]
This will do, thanks! Will comment again if I'll ever need the extra parameters.

**Comment by kobalicek** [comment]
Thanks for using exmodel, it's not really known library :)
